server:
  port: 8080
spring:
  application:
    name: OrderOnline
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/OrderOnlineDb
    username: postgres
    password: admin
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
        connection:
          isolation: 8
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

